# Generated by Django 2.0.7 on 2018-07-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
                ('prices', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('material', models.CharField(max_length=256)),
                ('sizes', models.CharField(max_length=256)),
                ('img_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('cond', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='services',
            field=models.ManyToManyField(to='api.Service'),
        ),
    ]
