# Generated by Django 2.0.7 on 2018-07-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='services',
            field=models.ManyToManyField(blank=True, to='api.Service'),
        ),
    ]
