# Generated by Django 2.0.7 on 2018-07-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180706_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='slug',
            new_name='slug',
        ),
    ]
