# Generated by Django 2.0.7 on 2018-07-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180717_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.CharField(blank=True, editable=False, max_length=256),
        ),
    ]
